# Site settings
title: Ben Bokser
email: bbokser@gmail.com
description: Ben Bokser's Portfolio
# baseurl: "/zetsu"
url: "http://bbokser.github.io"

author:
  name     : 'Benjamin Bokser'
  email    : bbokser@gmail.com
  url      : http://bbokser.github.io
  linkedin : https://www.linkedin.com/in/ben-bokser/
  twitter  : http://twitter.com/b_bokser

github: https://github.com/bbokser
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
