baseURL: "https://bbokser.github.io/"
disablePathToLower: true
languageCode: en-us
title: Ben Bokser
paginate: 25
theme: PaperMod
# publishDir: docs

minify:
    disableXML: true
    minifyOutput: true
    
params:
  fullWidthTheme: false
  centerTheme: true
