baseURL: "https://bbokser.github.io/"
disablePathToLower: true
languageCode: en-us
title: Ben Bokser's Blog
theme: ["PaperMod"]
# publishDir: docs

pagination:
  disableAliases: false
  pagerSize: 25
  path: page

minify:
    disableXML: true
    minifyOutput: true
    
# params:
#   fullWidthTheme: false
#   centerTheme: true

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
mainsections: ["posts", "papermod"]

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Ben Bokser's Blog"
    author: Ben Bokser
    title: Ben Bokser's Blog
    DateFormat: "January 2, 2006"
    customCSS: /style.css
    justifyContent: true
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    comments: true
    math: true
    enableEmoji: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    hidemeta: false
    hideSummary: false
    showtoc: true 
    tocopen: false
    # disqusShortname: ben_bokser
    # ShowFullTextinRSS: true https://medium.com/@ericapisani/setting-up-an-rss-feed-for-a-hugo-blog-using-the-papermod-theme-a141b3fa1ccd

    assets:
        disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/favicon.ico"
        favicon16x16:  "/favicon-16x16.png"
        favicon32x32:  "/favicon-32x32.png"
        apple_touch_icon:  "/apple-touch-icon.png"
        safari_pinned_tab:  "/safari-pinned-tab.svg"
    label:
        text: "Ben Bokser"
        # icon: ":deciduous_tree:" 
        iconHeight: 35

    profileMode:
        enabled: true
        title: Ben Bokser's Blog
        imageUrl: "images/portrait.jpg"
        imageTitle: my image
        imageWidth: 120
        imageHeight: 120
        buttons:
            - name: Posts
              url: posts

    # homeInfoParams:
    #     Title: "Ben Bokser's Blog"
    #     Content: >
    #         Welcome to my blog.

    socialIcons:
        - name: github
          url: "https://github.com/bbokser"
        - name: linkedin
          url: "https://www.linkedin.com/in/ben-bokser/"
        - name: youtube
          url: "https://www.youtube.com/@bbokser"
        - name: "rss"
          # url: "http://localhost:1313/index.xml"
          url: "https://bbokser.github.io/index.xml"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page

    editPost:
        URL: https://github.com/bbokser/bbokser.github.io/tree/main/content
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary


menu:
    main:
        - identifier: posts 
          name: Posts 
          url: /posts/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: archive 
          name: Archive 
          url: /archives/
          weight: 30
        - name: Portfolio
          url: https://benbokser.com/
          weight: 40
        # - identifier: search 
        #   name: Search 
        #   url: /search/ 
        #   weight: 60
        
 
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        # lineNos: true
        style: monokai

ignoreLogs: 'warning-goldmark-raw-html'